#!/usr/bin/env python
import os

env = SConscript("godot-cpp/SConstruct")

env["is_msvc"] = False
if env["platform"] == "windows" and not env.get("use_mingw"):
    env["is_msvc"] = True

# MinGW
if env["platform"] == "windows" and not env.get("is_msvc", False):
    # Tell SCons to use GCC's LTO-aware archiver and ranlib wrapper
    env["AR"] = "gcc-ar"
    env["RANLIB"] = "gcc-ranlib"

# This code uses C++17's std::optional and libopenmpt 0.7.x is also C++17
cpp14 = "-std=c++14"
cpp17 = "-std=c++17"
if env.get("is_msvc", False):
    cpp14 = "/std:c++14"
    cpp17 = "/std:c++17"
for i in range(len(env["CCFLAGS"])):
    if env["CCFLAGS"][i] == cpp14:
        env["CCFLAGS"][i] = cpp17
env.Append(CXXFLAGS=[cpp17])

openmpt_library = SConscript("../SCsub", exports="env")

opts = Variables([], ARGUMENTS)
opts.Add("target_name", "Name of the library to be built by SCons", "libgdmpt")
opts.Update(env)

if env["target"] == "release":
    if env.get("is_msvc", False):
        env.Append(LINKFLAGS=["/LTCG"])
    else:
        env.Append(LINKFLAGS=["-flto"])

env.Append(LIBS=[openmpt_library])
if env["platform"] == "windows":
    env.Append(LIBS=["Shlwapi"])  # Used by mpg123

env.Append(CPPPATH=["src/", "../openmpt"])
sources = Glob("src/*.cpp")

library = env.SharedLibrary(
    "project/bin/{}.{}.{}.{}{}".format(
        env["target_name"],
        env["platform"],
        env["target"],
        env["arch_suffix"],
        env["SHLIBSUFFIX"],
    ),
    source=sources,
)

Default(library)
